### PR TITLE
"Fix createStepNote method name"

### PR DESCRIPTION
**Pull request by pygoubet**

### CODE REVIEW

**Review by Raistlfiren — COMMENTED** [review]
The dry-run flag should do the same thing. Does that not suffice?

**Review by Raistlfiren — APPROVED** [review]
Nice catch on this one. Thank you!

**Comment by pygoubet** [comment]
> The dry-run flag should do the same thing. Does that not suffice?

Actually it does not permit to clean up workout list or schedule.
The "--dont-create" was an attempt to get this functionality.
It looks like that I have messed up my Pull Request. Sorry.
I have just fixed master branch to only contain the commit for "Fix createStepNote method name".

**Comment by Raistlfiren** [comment]
Thank you sir. I am merging this in!

**Pull request merged**
